dist: trusty
language: node_js

node_js:
  - "0.10"
  - "0.12"

before_install:
  - npm install -g coffee-script

install:
  - npm install

services:
  - mysql

before_script:
  - "mysql -e 'create database open_rest;'"

after_success:
  - codecov
